// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: service.proto

package grpc_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	YTDownloadService_SayHello_FullMethodName   = "/yt_downloader.YTDownloadService/SayHello"
	YTDownloadService_YTDownload_FullMethodName = "/yt_downloader.YTDownloadService/YTDownload"
)

// YTDownloadServiceClient is the client API for YTDownloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YTDownloadServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	YTDownload(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error)
}

type yTDownloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewYTDownloadServiceClient(cc grpc.ClientConnInterface) YTDownloadServiceClient {
	return &yTDownloadServiceClient{cc}
}

func (c *yTDownloadServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, YTDownloadService_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yTDownloadServiceClient) YTDownload(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadResponse)
	err := c.cc.Invoke(ctx, YTDownloadService_YTDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YTDownloadServiceServer is the server API for YTDownloadService service.
// All implementations must embed UnimplementedYTDownloadServiceServer
// for forward compatibility.
type YTDownloadServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	YTDownload(context.Context, *DownloadRequest) (*DownloadResponse, error)
	mustEmbedUnimplementedYTDownloadServiceServer()
}

// UnimplementedYTDownloadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedYTDownloadServiceServer struct{}

func (UnimplementedYTDownloadServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedYTDownloadServiceServer) YTDownload(context.Context, *DownloadRequest) (*DownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method YTDownload not implemented")
}
func (UnimplementedYTDownloadServiceServer) mustEmbedUnimplementedYTDownloadServiceServer() {}
func (UnimplementedYTDownloadServiceServer) testEmbeddedByValue()                           {}

// UnsafeYTDownloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YTDownloadServiceServer will
// result in compilation errors.
type UnsafeYTDownloadServiceServer interface {
	mustEmbedUnimplementedYTDownloadServiceServer()
}

func RegisterYTDownloadServiceServer(s grpc.ServiceRegistrar, srv YTDownloadServiceServer) {
	// If the following call pancis, it indicates UnimplementedYTDownloadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&YTDownloadService_ServiceDesc, srv)
}

func _YTDownloadService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDownloadServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YTDownloadService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDownloadServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _YTDownloadService_YTDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YTDownloadServiceServer).YTDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YTDownloadService_YTDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YTDownloadServiceServer).YTDownload(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// YTDownloadService_ServiceDesc is the grpc.ServiceDesc for YTDownloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YTDownloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yt_downloader.YTDownloadService",
	HandlerType: (*YTDownloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _YTDownloadService_SayHello_Handler,
		},
		{
			MethodName: "YTDownload",
			Handler:    _YTDownloadService_YTDownload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
